# Numpy

Numpy to biblioteka wykorzystywana do obliczeń numerycznych, udostępniająca wydajne implementacje operacji na wielowymiarowych tablicach.
## Tworzenie tablic `np.array`

In [1]:
import numpy as np

A = np.array([1, 2, 3])
print(A)

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(B)

C = np.zeros(5)
print(C)

D = np.arange(5)
print(D)

E = np.arange(12).reshape(4, 3)
print(E)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 0. 0.]
[0 1 2 3 4]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Indeksowanie

In [ ]:
print(A[1])

print(B[1, 1])

print(E[1:3, 1:])

## Operacje na tablicach numpy
Większość operacji na tablicach numpy jest zwektoryzowanych - działają poszczególnych na elementach tablic, a nie całych tablicach.

In [ ]:
X = np.arange(1, 10).reshape(3, 3)
Y = np.arange(10, 19).reshape(3, 3)
print("X:\n", X)
print("Y:\n", Y)
print("X + Y:\n", X + Y)
print("X * Y:\n", X * Y)
print("X / Y:\n", X / Y)
print("X @ Y:\n", X @ Y)

In [ ]:
print("np.log(X):\n", np.log(X))
print("np.exp(X):\n", np.exp(X))
print("np.sin(X):\n", np.sin(X))

In [ ]:
print("np.sum(X):\n", np.sum(X))
print("np.prod(X):\n", np.prod(X))
print("np.min(X):\n", np.min(X))
print("np.max(X):\n", np.max(X))

In [ ]:
X = list(np.random.randn(10**6))

In [2]:
%%timeit
sum(X)

NameError: name 'X' is not defined

In [ ]:
X = np.random.randn(10**6)

In [ ]:
%%timeit
np.sum(X)

# Pandas: podstawy

## Tworzenie `DataFrame`
`DataFrame` możemy stworzyć procedurą `pd.DataFrame()` podając `dict` zawierający kolumny, lub dwuwymiarową strukturę danych ([więcej informacji](https://pandas.pydata.org/docs/user_guide/dsintro.html#dataframe)). Alternatywą jest wczytanie z pliku, np. `pd.read_csv()`.

In [3]:
import pandas as pd
fruit = pd.DataFrame({"fruit": ["Apple", "Banana", "Orange"], "weight": [98.2, 116.5, 138.9], "kcal": [52, 88, 66]})
fruit

fruit  weight  kcal
0   Apple    98.2    52
1  Banana   116.5    88
2  Orange   138.9    66

In [ ]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df

In [ ]:
df1 = pd.DataFrame(np.arange(11, 20).reshape(3,3))
df1

In [8]:
mtcars = pd.read_csv("mtcars.csv") # Source: R (https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars)
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

## Sprawdzanie zawartości `DataFrame`
`pandas` zawiera kilka użytecznych funkcji, które pozwalają wstępnie zbadać zawartość `DataFrame`:
- `df.head()` - wyświetla kilka pierwszych wierszy,
- `df.info()` - podaje informacje o kolumnach,
- `df.describe()` - podaje statystyki opisowe dotyczące kolumn. 

In [2]:
mtcars.head()

NameError: name 'mtcars' is not defined

In [ ]:
mtcars.info()

In [ ]:
mtcars.describe()

Domyślnie, `describe()` podaje tylko statystyki dotyczące kolumn numerycznych. Możemy otrzymać też statystyki dla kolumn nienumerycznych podając `include='all'` lub `include='object`.

In [ ]:
mtcars.describe(include='all')

In [ ]:
mtcars.describe(include='object')

## Indeksowanie
### Wybieranie kolumn
Pojedyncze kolumny lub zbiory kolumn można wybierać na kilka sposobów:

In [ ]:
mtcars.mpg

In [7]:
mtcars["mpg"]

NameError: name 'mtcars' is not defined

In [ ]:
mtcars[["mpg", "wt", "hp"]]

## Wybieranie wierszy
Wiersze możemy wybierać także za pomocą operatora `[]` podając zakresy `low:high`.

In [ ]:
mtcars[3:4]

In [ ]:
mtcars[0:5]

## Wybieranie wierszy i kolumn
Zakresy wierszy i kolumn możemy wybierać za pomocą:
- `loc[]` - wybieramy za pomocą nazw
- `iloc[]` - wybieramy za pomocą indeksów liczbowych.

Przykładowo, wybierzmy wiersze 0-4 i kolumny `mpg`, `cyl`, `disp`.

In [ ]:
mtcars.loc[0:4, "mpg":"disp"]

In [ ]:
mtcars.iloc[0:5, 1:4]

Zwróćmy uwagę, że w `loc[]` podajemy zakresy domknięte, a w `iloc[]` otwarte. Możliwe jest też pominięcie jednej lub obu stron zakresu. W `loc[]` możemy podać też listę wierszy lub kolumn.

In [ ]:
mtcars.loc[:4, :"hp"]

In [ ]:
mtcars.loc[:, ["mpg", "hp"]]

## Indeksy
Etykiety wierszy i kolumn `DataFrame` przechowywane są w indeksach. Domyślnie, wczytując plik, pandas interpretuje pierwszy wiersz jako etykiety kolumn, a dla wierszy tworzy indeks liczbowy.

In [ ]:
mtcars.columns # Index zawiera etykiety kolumn

In [ ]:
mtcars.index # Index zawiera etykiety wierszy

Indeks wierszy nie musi być numeryczny. Mogą to być nazwy, lub np. daty. Jako indeks możemy wykorzystać jedną z kolumn, w tym przypadku `model`.

In [27]:
mtcars = mtcars.set_index("model")
mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model                                                                        
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
model                    
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

Teraz w `loc[]` możemy podać nazwę modelu.

In [29]:
mtcars.loc["Mazda RX4"]

mpg      21.00
cyl       6.00
disp    160.00
hp      110.00
drat      3.90
wt        2.62
qsec     16.46
vs        0.00
am        1.00
gear      4.00
carb      4.00
Name: Mazda RX4, dtype: float64

Możemy przywrócić domyślny indeks za pomocą `reset_index()`. Stary indeks zostanie zachowany jako kolumna.

In [ ]:
mtcars = mtcars.reset_index()
mtcars.head()

## Filtrowanie
Oprócz wybierania przy użyciu etykiet (`loc[]`) i indeksów liczbowych (`iloc[]`) pandas umożliwia także wybieranie przy użyciu wektorów binarnych (typu `bool`) o długości równej liczbie wierszy (lub kolumn). Wybrane zostaną te wiersze (lub kolumny), dla których w wektorze znajdzie się `True`. Umożliwia to filtrowanie danych względem zadanego kryterium. Przykładowo, wybrać wszystkie samochody dla których `hp >= 200` można w następujący sposób:

In [ ]:
mtcars[mtcars.hp >= 200]

W powyższym przykładzie, `mtcars.hp >= 200` tworzy wektor binarny, który następnie wykorzystuje do indeksowania `DataFrame`.

In [ ]:
vec = mtcars.hp >= 200
vec

In [ ]:
mtcars[vec]

Operacja `>=` jest **zwektoryzowana**, tak jak większość operacji na `DataFrame` i `Series`. To znaczy, że wykonywana jest na każdym elemencie ciągu, a nie na ciągu jako całości. Zwracaną wartością także jest ciąg. Podobnie działają np. operacje arytmetyczne. Przykładowo, poniższa operacja tworzy ciąg zawierający liczbę km/tonę dla każdego samochodu:

In [ ]:
mtcars.hp / mtcars.wt

Jeśli chcemy uwzględnić wiele kryteriów filtrowania, możemy wykorzystać operacje logiczne `&`, `|`, `~`. Uwaga: korzystamy tu z operatorów bitowych, a nie zwykłych (niezwektoryzowanych) operatorów logicznych (`and`, `or`, `not`). W poniższym przykładzie wybierzemy samochody o mocy powyżej 100 KM i wadze poniżej 3.5 t:

In [ ]:
mtcars[(mtcars.hp >= 100) & (mtcars.wt < 3.5)]

## Typy danych
Podstawowe typy danych obsługiwane przez pandas to:
- `int64` - liczby całkowite,
- `float64` - liczby zmiennoprzecinkowe,
- `bool` - wartości logiczne `True`/`False`
- `datetime64` - daty
- `object` - zwykle przechowuje `str` (napisy), ale może przechowywać obiekty dowolnego typu, lub różnych typów.
Więcej informacji na temat typów danych znajduje się w [dokumentacji](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes).

Typy danych możemy sprawdzić w następujący sposób:

In [ ]:
mtcars.dtypes

## Operacje na napisach
Operacje na napisach dostępne są po wybraniu danej kolumny a następnie `.str`. Przykładowo, aby zmienić nazwy modeli na wielkie litery, mogę użyć następującej metody:

In [ ]:
mtcars.model.str.upper().head(10)

Pełna lista dostępnych operacji znajduje się [tutaj](https://pandas.pydata.org/docs/reference/series.html#string-handling).
Przydatne są zwłaszcza operacje pozwalające filtrować przy użyciu RegEx. Na przykład, w następujący sposób można wybrać wszystkie Mercedesy i Mazdy:

In [ ]:
mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]

## Dodawanie i usuwanie danych
### Dodawanie kolumn
Nowe kolumny możemy tworzyć w następujący sposób:

In [ ]:
mtcars["n_wheels"] = 4
mtcars.head()

W powyższym przykładzie przypisujemy nowej kolumnie przypisujemy wartość skalarną, która jest propagowana na wszystkie wiersze.
Możemy też stworzyć nową kolumnę z Series lub innej sekwencji:

In [ ]:
mtcars["hp_per_ton"] = mtcars.hp / mtcars.wt
mtcars.head()

### Usuwanie wierszy i kolumn
Wiersze i kolumny możemy usuwać metodą `drop()` podając jako argument listę etykiet. 

In [ ]:
mtcars.drop([0, 1, 2]).head()

W poniższym przykładzie usuwane są wszystkie Mercedesy i Mazdy:

In [ ]:
merc_maz = mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]
mtcars = mtcars.drop(merc_maz.index)
mtcars.head()

Kolumny usuwamy dodając parametr `axis='columns'` lub `axis=1`.

In [ ]:
mtcars.drop(["n_wheels", "hp_per_ton"], axis='columns').head()

### Dodawanie wierszy
Wiersze najlepiej dodawać metodą `pd.concat()`.

In [ ]:
mtcars = pd.concat([mtcars, merc_maz])
mtcars

Nowe wiersze zostały dodane na końcu. Ponieważ zachowane zostały wartości indeksu, można przywrócić pierwotną kolejność sortując względem indeksu:

In [ ]:
mtcars = mtcars.sort_index()
mtcars

# Zadania
### Zadanie 1
Plik `SP500.csv` zawiera ceny otwarcia (`Open`), zamknięcia (`Close`), minimalną (`Low`), maksymalną (`High`) oraz wolumen obrotów (`Volume`) indeksu S&P 500 w latach 2018-2022.

1. Wczytaj plik jako `DataFrame` metodą `pd.read_csv()`.
2. Zbadaj zawartość metodami `head()`, `info()`, `describe()`.
3. Wybieranie:
    - Wybierz tylko kolumnę `Close`.
    - Wybierz kolumny `Date`, `Open`, `Close`
    - Wybierz 30. dzień notowań.
    - Wybierz 30 pierwszych dni notowań.
    - Wybierz ceny otwarcia i zamknięcia dla 30 pierwszych dni notowań.
4. Filtrowanie:
    - Znajdź dni, w których cena minimalna nie przekroczyła 2800.
    - Znajdź dni, w których wolumen obrotów przekroczył 2 500 000 000 a cena minimalna nie przekroczyła 3000.
    - Znajdź dni, w których wartość indeksu osiągnęła najwyższą i najniższą wartość. Wskazówka: skorzystaj z funkcji `max()` i `min()`.
    - Znajdź dni, w których cena otwarcia przekroczyła średnią cenę otwarcia. Wskazówka: skorzystaj z funkcji `mean()`.
5. Dodawanie i usuwanie:
    - Stwórz nową kolumnę zawierającą różnicę między ceną maksymalną a minimalną danego dnia.
    - Stwórz nową kolumnę zawierającą odchylenie ceny otwarcia od średniej ceny otwarcia.
    - Usuń kolumnę `Volume`.
    - Usuń wiersze zawierające notowania z roku 2018.
    - W pliku `SP500Jan2023.csv` znajdują się dane ze stycznia 2023. Wczytaj go i dodaj zawartość do zbioru. Pamiętaj o kolumnach dodanych i usuniętych we wcześniejszych podpunktach. Co dzieje się w przypadku braku zgodności kolumn? Sprawdź w dokumentacji [`pd.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat), który parametr kontroluje to, co metoda robi w tej sytuacji.

### Zadanie 2
Wczytaj zbiory w plikach `life_expectancy_years.csv` i `housing.csv`. Eksploruj je za pomocą poznanych metod. Zanotuj swoje obserwacje.


In [4]:
ley = pd.read_csv('life_expectancy_years.csv')
ley.head()

country  1800  1801  1802  1803  1804  1805  1806  1807  1808  \
0           Afghanistan  28.2  28.2  28.2  28.2  28.2  28.2  28.1  28.1  28.1   
1                Angola  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0  27.0   
2               Albania  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4  35.4   
3               Andorra   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4  United Arab Emirates  30.7  30.7  30.7  30.7  30.7  30.7  30.7  30.7  30.7   

   ...  2091  2092  2093  2094  2095  2096  2097  2098  2099  2100  
0  ...  75.5  75.7  75.8  76.0  76.1  76.2  76.4  76.5  76.6  76.8  
1  ...  78.8  79.0  79.1  79.2  79.3  79.5  79.6  79.7  79.9  80.0  
2  ...  87.4  87.5  87.6  87.7  87.8  87.9  88.0  88.2  88.3  88.4  
3  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4  ...  82.4  82.5  82.6  82.7  82.8  82.9  83.0  83.1  83.2  83.3  

[5 rows x 302 columns]

In [5]:
ley.describe()

1800        1801        1802        1803        1804        1805  \
count  186.000000  186.000000  186.000000  186.000000  186.000000  186.000000   
mean    31.503763   31.463441   31.480108   31.385484   31.460753   31.586559   
std      3.809510    3.801217    3.932344    3.955872    3.928388    4.003874   
min     23.400000   23.400000   23.400000   19.600000   23.400000   23.400000   
25%     29.025000   28.925000   28.900000   28.900000   28.925000   29.025000   
50%     31.750000   31.650000   31.550000   31.500000   31.550000   31.650000   
75%     33.875000   33.900000   33.875000   33.675000   33.775000   33.875000   
max     42.900000   40.300000   44.400000   44.800000   42.800000   44.300000   

             1806        1807        1808        1809  ...        2091  \
count  186.000000  186.000000  186.000000  186.000000  ...  186.000000   
mean    31.644086   31.598387   31.385484   31.313441  ...   83.361828   
std      4.102694    3.974506    4.080230    4.033412  ...    5.803782   
min     23.400000   23.400000   12.500000   13.400000  ...   66.400000   
25%     29.025000   29.025000   28.925000   28.825000  ...   79.650000   
50%     31.750000   31.750000   31.550000   31.500000  ...   84.000000   
75%     33.975000   33.975000   33.775000   33.675000  ...   87.775000   
max     45.800000   43.600000   43.500000   41.700000  ...   93.400000   

             2092        2093        2094        2095        2096        2097  \
count  186.000000  186.000000  186.000000  186.000000  186.000000  186.000000   
mean    83.476344   83.600538   83.717742   83.838172   83.955376   84.076344   
std      5.797854    5.788922    5.777904    5.770755    5.766333    5.756555   
min     66.500000   66.700000   66.800000   66.900000   67.000000   67.100000   
25%     79.750000   79.925000   80.025000   80.150000   80.325000   80.425000   
50%     84.100000   84.250000   84.300000   84.500000   84.600000   84.700000   
75%     87.875000   87.975000   88.075000   88.175000   88.300000   88.400000   
max     93.500000   93.600000   93.700000   93.800000   94.000000   94.100000   

             2098        2099        2100  
count  186.000000  186.000000  186.000000  
mean    84.193548   84.312903   84.430645  
std      5.750616    5.743805    5.741341  
min     67.200000   67.300000   67.400000  
25%     80.525000   80.700000   80.800000  
50%     84.800000   84.900000   85.000000  
75%     88.500000   88.675000   88.775000  
max     94.200000   94.300000   94.400000  

[8 rows x 301 columns]

In [12]:
ley[['country', '1800', '1900', '2000', '2023', '2100']].head()

country  1800  1900  2000  2023  2100
0           Afghanistan  28.2  33.3  54.7  64.6  76.8
1                Angola  27.0  32.6  52.8  66.4  80.0
2               Albania  35.4  34.9  75.4  79.0  88.4
3               Andorra   NaN   NaN  80.8   NaN   NaN
4  United Arab Emirates  30.7  35.4  69.1  74.4  83.3

In [13]:
ley[['country', '1800', '1900', '2000', '2023', '2100']].describe()

1800        1900        2000        2023        2100
count  186.000000  186.000000  195.000000  186.000000  186.000000
mean    31.503763   34.215054   67.489231   73.645161   84.430645
std      3.809510    6.192340    9.487188    6.818734    5.741341
min     23.400000   20.100000   43.800000   53.300000   67.400000
25%     29.025000   30.450000   60.800000   68.250000   80.800000
50%     31.750000   33.700000   70.300000   74.400000   85.000000
75%     33.875000   36.325000   74.700000   78.575000   88.775000
max     42.900000   53.600000   81.600000   85.400000   94.400000

In [17]:
some_years = ley[['country', '1800', '1900', '2000', '2023', '2100']]
some_years[some_years['2023'].notnull()].sort_values(by=['2023'])

country  1800  1900  2000  2023  2100
102                   Lesotho  32.8  36.1  48.5  53.3  69.2
28   Central African Republic  30.0  33.8  43.8  53.6  67.4
165                  Eswatini  32.3  33.1  48.3  59.5  71.8
157                   Somalia  29.4  33.1  51.4  59.6  73.0
153           Solomon Islands  25.1  24.6  57.0  59.6  67.7
..                        ...   ...   ...   ...   ...   ...
30                Switzerland  38.0  47.5  80.3  84.5  93.3
82                    Iceland  42.9  46.8  80.3  84.7  93.4
72           Hong Kong, China  34.9  34.9  80.4  85.0  93.8
87                      Japan  36.4  38.7  81.6  85.3  94.0
152                 Singapore  29.1  33.7  79.4  85.4  94.4

[186 rows x 6 columns]

In [18]:
some_years[some_years['1900'].notnull()].sort_values(by=['1900'])

country  1800  1900  2000  2023  2100
78          India  25.4  20.1  62.9  71.7  83.3
15     Bangladesh  25.5  21.2  65.5  75.7  88.7
134      Pakistan  25.8  23.3  61.0  66.5  76.1
172  Turkmenistan  24.0  24.0  66.3  71.3  81.3
148        Rwanda  31.8  24.3  50.5  69.8  83.1
..            ...   ...   ...   ...   ...   ...
79        Ireland  38.3  49.2  76.8  82.6  91.5
8       Australia  34.0  50.0  79.7  83.5  92.3
47        Denmark  37.4  52.0  77.2  81.7  90.8
164        Sweden  32.2  52.3  80.0  83.4  92.1
129        Norway  37.9  53.6  78.9  83.5  92.3

[186 rows x 6 columns]

In [19]:
some_years[some_years['2000'].notnull()].sort_values(by=['2000'])

country  1800  1900  2000  2023  2100
28   Central African Republic  30.0  33.8  43.8  53.6  67.4
11                    Burundi  31.5  32.0  44.7  65.2  80.1
193                    Zambia  32.6  34.3  45.3  64.2  77.1
27                   Botswana  33.6  35.4  45.5  62.7  71.6
122                    Malawi  30.3  29.8  45.9  66.3  82.1
..                        ...   ...   ...   ...   ...   ...
82                    Iceland  42.9  46.8  80.3  84.7  93.4
72           Hong Kong, China  34.9  34.9  80.4  85.0  93.8
3                     Andorra   NaN   NaN  80.8   NaN   NaN
156                San Marino   NaN   NaN  81.5   NaN   NaN
87                      Japan  36.4  38.7  81.6  85.3  94.0

[195 rows x 6 columns]

In [42]:
some_years = some_years.set_index('country')

In [43]:
some_years.loc['India']

1800    25.4
1900    20.1
2000    62.9
2023    71.7
2100    83.3
Name: India, dtype: float64

In [45]:
some_years[some_years['2023'].notnull()].sort_values(by=['2023']).index.get_loc('Ukraine')

93