# Numpy

Numpy to biblioteka wykorzystywana do obliczeń numerycznych, udostępniająca wydajne implementacje operacji na wielowymiarowych tablicach.
## Tworzenie tablic `np.array`

In [1]:
import numpy as np

A = np.array([1, 2, 3])
print(A)

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(B)

C = np.zeros(5)
print(C)

D = np.arange(5)
print(D)

E = np.arange(12).reshape(4, 3)
print(E)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 0. 0.]
[0 1 2 3 4]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Indeksowanie

In [2]:
print(A[1])

print(B[1, 1])

print(E[1:3, 1:])

2
5
[[4 5]
 [7 8]]


## Operacje na tablicach numpy
Większość operacji na tablicach numpy jest zwektoryzowanych - działają poszczególnych na elementach tablic, a nie całych tablicach.

In [3]:
X = np.arange(1, 10).reshape(3, 3)
Y = np.arange(10, 19).reshape(3, 3)
print("X:\n", X)
print("Y:\n", Y)
print("X + Y:\n", X + Y)
print("X * Y:\n", X * Y)
print("X / Y:\n", X / Y)
print("X @ Y:\n", X @ Y)

X:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Y:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
X + Y:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
X * Y:
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
X / Y:
 [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
X @ Y:
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [4]:
print("np.log(X):\n", np.log(X))
print("np.exp(X):\n", np.exp(X))
print("np.sin(X):\n", np.sin(X))

np.log(X):
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
np.exp(X):
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
np.sin(X):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [5]:
print("np.sum(X):\n", np.sum(X))
print("np.prod(X):\n", np.prod(X))
print("np.min(X):\n", np.min(X))
print("np.max(X):\n", np.max(X))

np.sum(X):
 45
np.prod(X):
 362880
np.min(X):
 1
np.max(X):
 9


In [12]:
X = list(np.random.randn(10**6))

In [13]:
%%timeit
sum(X)

146 ms ± 4.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
X = np.random.randn(10**6)

In [15]:
%%timeit
np.sum(X)

407 µs ± 1.51 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Pandas: podstawy

## Tworzenie `DataFrame`
`DataFrame` możemy stworzyć procedurą `pd.DataFrame()` podając `dict` zawierający kolumny, lub dwuwymiarową strukturę danych ([więcej informacji](https://pandas.pydata.org/docs/user_guide/dsintro.html#dataframe)). Alternatywą jest wczytanie z pliku, np. `pd.read_csv()`.

In [2]:
import pandas as pd
fruit = pd.DataFrame({"fruit": ["Apple", "Banana", "Orange"], "weight": [98.2, 116.5, 138.9], "kcal": [52, 88, 66]})
fruit

fruit  weight  kcal
0   Apple    98.2    52
1  Banana   116.5    88
2  Orange   138.9    66

In [17]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [18]:
df1 = pd.DataFrame(np.arange(11, 20).reshape(3,3))
df1

0   1   2
0  11  12  13
1  14  15  16
2  17  18  19

In [19]:
mtcars = pd.read_csv("mtcars.csv") # Source: R (https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars)
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

## Sprawdzanie zawartości `DataFrame`
`pandas` zawiera kilka użytecznych funkcji, które pozwalają wstępnie zbadać zawartość `DataFrame`:
- `df.head()` - wyświetla kilka pierwszych wierszy,
- `df.info()` - podaje informacje o kolumnach,
- `df.describe()` - podaje statystyki opisowe dotyczące kolumn. 

In [20]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [21]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [22]:
mtcars.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

Domyślnie, `describe()` podaje tylko statystyki dotyczące kolumn numerycznych. Możemy otrzymać też statystyki dla kolumn nienumerycznych podając `include='all'` lub `include='object`.

In [23]:
mtcars.describe(include='all')

model        mpg        cyl        disp          hp       drat  \
count          32  32.000000  32.000000   32.000000   32.000000  32.000000   
unique         32        NaN        NaN         NaN         NaN        NaN   
top     Mazda RX4        NaN        NaN         NaN         NaN        NaN   
freq            1        NaN        NaN         NaN         NaN        NaN   
mean          NaN  20.090625   6.187500  230.721875  146.687500   3.596563   
std           NaN   6.026948   1.785922  123.938694   68.562868   0.534679   
min           NaN  10.400000   4.000000   71.100000   52.000000   2.760000   
25%           NaN  15.425000   4.000000  120.825000   96.500000   3.080000   
50%           NaN  19.200000   6.000000  196.300000  123.000000   3.695000   
75%           NaN  22.800000   8.000000  326.000000  180.000000   3.920000   
max           NaN  33.900000   8.000000  472.000000  335.000000   4.930000   

               wt       qsec         vs         am       gear     carb  
count   32.000000  32.000000  32.000000  32.000000  32.000000  32.0000  
unique        NaN        NaN        NaN        NaN        NaN      NaN  
top           NaN        NaN        NaN        NaN        NaN      NaN  
freq          NaN        NaN        NaN        NaN        NaN      NaN  
mean     3.217250  17.848750   0.437500   0.406250   3.687500   2.8125  
std      0.978457   1.786943   0.504016   0.498991   0.737804   1.6152  
min      1.513000  14.500000   0.000000   0.000000   3.000000   1.0000  
25%      2.581250  16.892500   0.000000   0.000000   3.000000   2.0000  
50%      3.325000  17.710000   0.000000   0.000000   4.000000   2.0000  
75%      3.610000  18.900000   1.000000   1.000000   4.000000   4.0000  
max      5.424000  22.900000   1.000000   1.000000   5.000000   8.0000

In [24]:
mtcars.describe(include='object')

model
count          32
unique         32
top     Mazda RX4
freq            1

## Indeksowanie
### Wybieranie kolumn
Pojedyncze kolumny lub zbiory kolumn można wybierać na kilka sposobów:

In [25]:
mtcars.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [26]:
mtcars["mpg"]

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [27]:
mtcars[["mpg", "wt", "hp"]]

mpg     wt   hp
0   21.0  2.620  110
1   21.0  2.875  110
2   22.8  2.320   93
3   21.4  3.215  110
4   18.7  3.440  175
5   18.1  3.460  105
6   14.3  3.570  245
7   24.4  3.190   62
8   22.8  3.150   95
9   19.2  3.440  123
10  17.8  3.440  123
11  16.4  4.070  180
12  17.3  3.730  180
13  15.2  3.780  180
14  10.4  5.250  205
15  10.4  5.424  215
16  14.7  5.345  230
17  32.4  2.200   66
18  30.4  1.615   52
19  33.9  1.835   65
20  21.5  2.465   97
21  15.5  3.520  150
22  15.2  3.435  150
23  13.3  3.840  245
24  19.2  3.845  175
25  27.3  1.935   66
26  26.0  2.140   91
27  30.4  1.513  113
28  15.8  3.170  264
29  19.7  2.770  175
30  15.0  3.570  335
31  21.4  2.780  109

## Wybieranie wierszy
Wiersze możemy wybierać także za pomocą operatora `[]` podając zakresy `low:high`.

In [28]:
mtcars[3:4]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
3  Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   

   carb  
3     1

In [29]:
mtcars[0:5]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

## Wybieranie wierszy i kolumn
Zakresy wierszy i kolumn możemy wybierać za pomocą:
- `loc[]` - wybieramy za pomocą nazw
- `iloc[]` - wybieramy za pomocą indeksów liczbowych.

Przykładowo, wybierzmy wiersze 0-4 i kolumny `mpg`, `cyl`, `disp`.

In [30]:
mtcars.loc[0:4, "mpg":"disp"]

mpg  cyl   disp
0  21.0    6  160.0
1  21.0    6  160.0
2  22.8    4  108.0
3  21.4    6  258.0
4  18.7    8  360.0

In [31]:
mtcars.iloc[0:5, 1:4]

mpg  cyl   disp
0  21.0    6  160.0
1  21.0    6  160.0
2  22.8    4  108.0
3  21.4    6  258.0
4  18.7    8  360.0

Zwróćmy uwagę, że w `loc[]` podajemy zakresy domknięte, a w `iloc[]` otwarte. Możliwe jest też pominięcie jednej lub obu stron zakresu. W `loc[]` możemy podać też listę wierszy lub kolumn.

In [32]:
mtcars.loc[:4, :"hp"]

model   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  160.0  110
1      Mazda RX4 Wag  21.0    6  160.0  110
2         Datsun 710  22.8    4  108.0   93
3     Hornet 4 Drive  21.4    6  258.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [33]:
mtcars.loc[:, ["mpg", "hp"]]

mpg   hp
0   21.0  110
1   21.0  110
2   22.8   93
3   21.4  110
4   18.7  175
5   18.1  105
6   14.3  245
7   24.4   62
8   22.8   95
9   19.2  123
10  17.8  123
11  16.4  180
12  17.3  180
13  15.2  180
14  10.4  205
15  10.4  215
16  14.7  230
17  32.4   66
18  30.4   52
19  33.9   65
20  21.5   97
21  15.5  150
22  15.2  150
23  13.3  245
24  19.2  175
25  27.3   66
26  26.0   91
27  30.4  113
28  15.8  264
29  19.7  175
30  15.0  335
31  21.4  109

## Indeksy
Etykiety wierszy i kolumn `DataFrame` przechowywane są w indeksach. Domyślnie, wczytując plik, pandas interpretuje pierwszy wiersz jako etykiety kolumn, a dla wierszy tworzy indeks liczbowy.

In [34]:
mtcars.columns # Index zawiera etykiety kolumn

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [35]:
mtcars.index # Index zawiera etykiety wierszy

RangeIndex(start=0, stop=32, step=1)

Indeks wierszy nie musi być numeryczny. Mogą to być nazwy, lub np. daty. Jako indeks możemy wykorzystać jedną z kolumn, w tym przypadku `model`.

In [36]:
mtcars = mtcars.set_index("model")
mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model                                                                        
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
model                    
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

Teraz w `loc[]` możemy podać nazwę modelu.

In [37]:
mtcars.loc["Merc 240D":"Merc 450SLC"]

mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
model                                                                   
Merc 240D    24.4    4  146.7   62  3.69  3.19  20.0   1   0     4     2
Merc 230     22.8    4  140.8   95  3.92  3.15  22.9   1   0     4     2
Merc 280     19.2    6  167.6  123  3.92  3.44  18.3   1   0     4     4
Merc 280C    17.8    6  167.6  123  3.92  3.44  18.9   1   0     4     4
Merc 450SE   16.4    8  275.8  180  3.07  4.07  17.4   0   0     3     3
Merc 450SL   17.3    8  275.8  180  3.07  3.73  17.6   0   0     3     3
Merc 450SLC  15.2    8  275.8  180  3.07  3.78  18.0   0   0     3     3

Możemy przywrócić domyślny indeks za pomocą `reset_index()`. Stary indeks zostanie zachowany jako kolumna.

In [38]:
mtcars = mtcars.reset_index()
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

## Filtrowanie
Oprócz wybierania przy użyciu etykiet (`loc[]`) i indeksów liczbowych (`iloc[]`) pandas umożliwia także wybieranie przy użyciu wektorów binarnych (typu `bool`) o długości równej liczbie wierszy (lub kolumn). Wybrane zostaną te wiersze (lub kolumny), dla których w wektorze znajdzie się `True`. Umożliwia to filtrowanie danych względem zadanego kryterium. Przykładowo, wybrać wszystkie samochody dla których `hp >= 200` można w następujący sposób:

In [39]:
mtcars[mtcars.hp >= 200]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
6      3     4  
14     3     4  
15     3     4  
16     3     4  
23     3     4  
28     5     4  
30     5     8

W powyższym przykładzie, `mtcars.hp >= 200` tworzy wektor binarny, który następnie wykorzystuje do indeksowania `DataFrame`.

In [40]:
vec = mtcars.hp >= 200
vec

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27    False
28     True
29    False
30     True
31    False
Name: hp, dtype: bool

In [41]:
mtcars[vec]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
6      3     4  
14     3     4  
15     3     4  
16     3     4  
23     3     4  
28     5     4  
30     5     8

Operacja `>=` jest **zwektoryzowana**, tak jak większość operacji na `DataFrame` i `Series`. To znaczy, że wykonywana jest na każdym elemencie ciągu, a nie na ciągu jako całości. Zwracaną wartością także jest ciąg. Podobnie działają np. operacje arytmetyczne. Przykładowo, poniższa operacja tworzy ciąg zawierający liczbę km/tonę dla każdego samochodu:

In [42]:
mtcars.hp / mtcars.wt

0     41.984733
1     38.260870
2     40.086207
3     34.214619
4     50.872093
5     30.346821
6     68.627451
7     19.435737
8     30.158730
9     35.755814
10    35.755814
11    44.226044
12    48.257373
13    47.619048
14    39.047619
15    39.638643
16    43.030870
17    30.000000
18    32.198142
19    35.422343
20    39.350913
21    42.613636
22    43.668122
23    63.802083
24    45.513654
25    34.108527
26    42.523364
27    74.686054
28    83.280757
29    63.176895
30    93.837535
31    39.208633
dtype: float64

Jeśli chcemy uwzględnić wiele kryteriów filtrowania, możemy wykorzystać operacje logiczne `&`, `|`, `~`. Uwaga: korzystamy tu z operatorów bitowych, a nie zwykłych (niezwektoryzowanych) operatorów logicznych (`and`, `or`, `not`). W poniższym przykładzie wybierzemy samochody o mocy powyżej 100 KM i wadze poniżej 3.5 t:

In [43]:
mtcars[(mtcars.hp >= 100) & (mtcars.wt < 3.5)]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0           Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1       Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
3      Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4   Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5             Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
9            Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10          Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
22        AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
27       Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28     Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29       Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
31         Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
3      3     1  
4      3     2  
5      3     1  
9      4     4  
10     4     4  
22     3     2  
27     5     2  
28     5     4  
29     5     6  
31     4     2

## Typy danych
Podstawowe typy danych obsługiwane przez pandas to:
- `int64` - liczby całkowite,
- `float64` - liczby zmiennoprzecinkowe,
- `bool` - wartości logiczne `True`/`False`
- `datetime64` - daty
- `object` - zwykle przechowuje `str` (napisy), ale może przechowywać obiekty dowolnego typu, lub różnych typów.
Więcej informacji na temat typów danych znajduje się w [dokumentacji](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes).

Typy danych możemy sprawdzić w następujący sposób:

In [44]:
mtcars.dtypes

model     object
mpg      float64
cyl        int64
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs         int64
am         int64
gear       int64
carb       int64
dtype: object

## Operacje na napisach
Operacje na napisach dostępne są po wybraniu danej kolumny a następnie `.str`. Przykładowo, aby zmienić nazwy modeli na wielkie litery, mogę użyć następującej metody:

In [45]:
mtcars.model.str.upper().head(10)

0            MAZDA RX4
1        MAZDA RX4 WAG
2           DATSUN 710
3       HORNET 4 DRIVE
4    HORNET SPORTABOUT
5              VALIANT
6           DUSTER 360
7            MERC 240D
8             MERC 230
9             MERC 280
Name: model, dtype: object

Pełna lista dostępnych operacji znajduje się [tutaj](https://pandas.pydata.org/docs/reference/series.html#string-handling).
Przydatne są zwłaszcza operacje pozwalające filtrować przy użyciu RegEx. Na przykład, w następujący sposób można wybrać wszystkie Mercedesy i Mazdy:

In [46]:
mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]

C:\Users\s31056\AppData\Local\Temp\ipykernel_11284\2120074580.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]


model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0       Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1   Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
7       Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8        Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
9        Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
10      Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
11     Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
12     Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
13    Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   

    carb  
0      4  
1      4  
7      2  
8      2  
9      4  
10     4  
11     3  
12     3  
13     3

## Dodawanie i usuwanie danych
### Dodawanie kolumn
Nowe kolumny możemy tworzyć w następujący sposób:

In [47]:
mtcars["n_wheels"] = 4
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  n_wheels  
0     4         4  
1     4         4  
2     1         4  
3     1         4  
4     2         4

W powyższym przykładzie przypisujemy nowej kolumnie przypisujemy wartość skalarną, która jest propagowana na wszystkie wiersze.
Możemy też stworzyć nową kolumnę z Series lub innej sekwencji:

In [48]:
mtcars["hp_per_ton"] = mtcars.hp / mtcars.wt
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  n_wheels  hp_per_ton  
0     4         4   41.984733  
1     4         4   38.260870  
2     1         4   40.086207  
3     1         4   34.214619  
4     2         4   50.872093

### Usuwanie wierszy i kolumn
Wiersze i kolumny możemy usuwać metodą `drop()` podając jako argument listę etykiet. 

In [49]:
mtcars.drop([0, 1, 2]).head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
7          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   

   carb  n_wheels  hp_per_ton  
3     1         4   34.214619  
4     2         4   50.872093  
5     1         4   30.346821  
6     4         4   68.627451  
7     2         4   19.435737

W poniższym przykładzie usuwane są wszystkie Mercedesy i Mazdy:

In [50]:
merc_maz = mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]
mtcars = mtcars.drop(merc_maz.index)
mtcars.head()

C:\Users\s31056\AppData\Local\Temp\ipykernel_11284\4039388994.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merc_maz = mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]


model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   

   carb  n_wheels  hp_per_ton  
2     1         4   40.086207  
3     1         4   34.214619  
4     2         4   50.872093  
5     1         4   30.346821  
6     4         4   68.627451

Kolumny usuwamy dodając parametr `axis='columns'` lub `axis=1`.

In [51]:
mtcars.drop(["n_wheels", "hp_per_ton"], axis='columns').head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   

   carb  
2     1  
3     1  
4     2  
5     1  
6     4

### Dodawanie wierszy
Wiersze najlepiej dodawać metodą `pd.concat()`.

In [52]:
mtcars = pd.concat([mtcars, merc_maz])
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   

    gear  carb  n_wheels  hp_per_ton  
2      4     1         4   40.086207  
3      3     1         4   34.214619  
4      3     2         4   50.872093  
5      3     1         4   30.346821  
6      3     4         4   68.627451  
14     3     4         4   39.047619  
15     3     4         4   39.638643  
16     3     4         4   43.030870  
17     4     1         4   30.000000  
18     4     2         4   32.198142  
19     4     1         4   35.422343  
20     3     1         4   39.350913  
21     3     2         4   42.613636  
22     3     2         4   43.668122  
23     3     4         4   63.802083  
24     3     2         4   45.513654  
25     4     1         4   34.108527  
26     5     2         4   42.523364  
27     5     2         4   74.686054  
28     5     4         4   83.280757  
29     5     6         4   63.176895  
30     5     8         4   93.837535  
31     4     2         4   39.208633  
0      4     4         4   41.984733  
1      4     4         4   38.260870  
7      4     2         4   19.435737  
8      4     2         4   30.158730  
9      4     4         4   35.755814  
10     4     4         4   35.755814  
11     3     3         4   44.226044  
12     3     3         4   48.257373  
13     3     3         4   47.619048

Nowe wiersze zostały dodane na końcu. Ponieważ zachowane zostały wartości indeksu, można przywrócić pierwotną kolejność sortując względem indeksu:

In [53]:
mtcars = mtcars.sort_index()
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  n_wheels  hp_per_ton  
0      4     4         4   41.984733  
1      4     4         4   38.260870  
2      4     1         4   40.086207  
3      3     1         4   34.214619  
4      3     2         4   50.872093  
5      3     1         4   30.346821  
6      3     4         4   68.627451  
7      4     2         4   19.435737  
8      4     2         4   30.158730  
9      4     4         4   35.755814  
10     4     4         4   35.755814  
11     3     3         4   44.226044  
12     3     3         4   48.257373  
13     3     3         4   47.619048  
14     3     4         4   39.047619  
15     3     4         4   39.638643  
16     3     4         4   43.030870  
17     4     1         4   30.000000  
18     4     2         4   32.198142  
19     4     1         4   35.422343  
20     3     1         4   39.350913  
21     3     2         4   42.613636  
22     3     2         4   43.668122  
23     3     4         4   63.802083  
24     3     2         4   45.513654  
25     4     1         4   34.108527  
26     5     2         4   42.523364  
27     5     2         4   74.686054  
28     5     4         4   83.280757  
29     5     6         4   63.176895  
30     5     8         4   93.837535  
31     4     2         4   39.208633

# Zadania
### Zadanie 1
Plik `SP500.csv` zawiera ceny otwarcia (`Open`), zamknięcia (`Close`), minimalną (`Low`), maksymalną (`High`) oraz wolumen obrotów (`Volume`) indeksu S&P 500 w latach 2018-2022.

1. Wczytaj plik jako `DataFrame` metodą `pd.read_csv()`.
2. Zbadaj zawartość metodami `head()`, `info()`, `describe()`.
3. Wybieranie:
    - Wybierz tylko kolumnę `Close`.
    - Wybierz kolumny `Date`, `Open`, `Close`
    - Wybierz 30. dzień notowań.
    - Wybierz 30 pierwszych dni notowań.
    - Wybierz ceny otwarcia i zamknięcia dla 30 pierwszych dni notowań.
4. Filtrowanie:
    - Znajdź dni, w których cena minimalna nie przekroczyła 2800.
    - Znajdź dni, w których wolumen obrotów przekroczył 2 500 000 000 a cena minimalna nie przekroczyła 3000.
    - Znajdź dni, w których wartość indeksu osiągnęła najwyższą i najniższą wartość. Wskazówka: skorzystaj z funkcji `max()` i `min()`.
    - Znajdź dni, w których cena otwarcia przekroczyła średnią cenę otwarcia. Wskazówka: skorzystaj z funkcji `mean()`.
5. Dodawanie i usuwanie:
    - Stwórz nową kolumnę zawierającą różnicę między ceną maksymalną a minimalną danego dnia.
    - Stwórz nową kolumnę zawierającą odchylenie ceny otwarcia od średniej ceny otwarcia.
    - Usuń kolumnę `Volume`.
    - Usuń wiersze zawierające notowania z roku 2018.
    - W pliku `SP500Jan2023.csv` znajdują się dane ze stycznia 2023. Wczytaj go i dodaj zawartość do zbioru. Pamiętaj o kolumnach dodanych i usuniętych we wcześniejszych podpunktach. Co dzieje się w przypadku braku zgodności kolumn? Sprawdź w dokumentacji [`pd.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat), który parametr kontroluje to, co metoda robi w tej sytuacji.

### Zadanie 2
Wczytaj zbiory w plikach `life_expectancy_years.csv` i `housing.csv`. Eksploruj je za pomocą poznanych metod. Zanotuj swoje obserwacje.


In [27]:
ley = pd.read_csv('life_expectancy_years.csv')
ley.head()
ley.describe()
ley[['country', '1800', '1900', '2000', '2023', '2100']].head()
ley[['country', '1800', '1900', '2000', '2023', '2100']].describe()
some_years = ley[['country', '1800', '1900', '2000', '2023', '2100']]
some_years[some_years['2023'].notnull()].sort_values(by=['2023'])
some_years[some_years['1900'].notnull()].sort_values(by=['1900'])
some_years[some_years['2000'].notnull()].sort_values(by=['2000'])
some_years = some_years.set_index('country')
some_years.loc['India']
some_years[some_years['2023'].notnull()].sort_values(by=['2023']).index.get_loc('Ukraine')

93

In [28]:
h = pd.read_csv('housing.csv')
h.head()
h.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [23]:
h["bedrooms_per_room"] = h.total_bedrooms / h.total_rooms
h.sort_values(by='bedrooms_per_room', ascending= False).head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
19435    -121.04     37.67                16.0         19.0            19.0   
5916     -118.44     34.28                46.0         11.0            11.0   
3126     -117.79     35.21                 4.0          2.0             2.0   
17820    -121.90     37.37                20.0         78.0            72.0   
4552     -118.24     34.04                52.0        116.0           107.0   

       population  households  median_income  median_house_value  \
19435       166.0         9.0         0.5360            162500.0   
5916         24.0        13.0         2.8750            162500.0   
3126          6.0         2.0         2.3750            137500.0   
17820       120.0        69.0         1.0938            187500.0   
4552        171.0        92.0         1.0769            112500.0   

      ocean_proximity  bedrooms_per_room  
19435          INLAND           1.000000  
5916        <1H OCEAN           1.000000  
3126           INLAND           1.000000  
17820       <1H OCEAN           0.923077  
4552        <1H OCEAN           0.922414

In [9]:
proximities = h['ocean_proximity'].unique()
proximities

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [19]:
h.groupby('ocean_proximity')['median_income'].mean().sort_values()

ocean_proximity
ISLAND        2.744420
INLAND        3.208996
NEAR OCEAN    4.005785
NEAR BAY      4.172885
<1H OCEAN     4.230682
Name: median_income, dtype: float64

In [20]:
h.groupby('ocean_proximity')['median_house_value'].mean().sort_values()

ocean_proximity
INLAND        124805.392001
<1H OCEAN     240084.285464
NEAR OCEAN    249433.977427
NEAR BAY      259212.311790
ISLAND        380440.000000
Name: median_house_value, dtype: float64

In [21]:
h.groupby('ocean_proximity')['housing_median_age'].mean().sort_values()

ocean_proximity
INLAND        24.271867
<1H OCEAN     29.279225
NEAR OCEAN    29.347254
NEAR BAY      37.730131
ISLAND        42.400000
Name: housing_median_age, dtype: float64

In [24]:
h.sort_values(by = 'population')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5342     -118.44     34.04                16.0         18.0             6.0   
12458    -114.62     33.62                26.0         18.0             3.0   
3126     -117.79     35.21                 4.0          2.0             2.0   
12286    -116.95     33.86                 1.0          6.0             2.0   
18210    -122.06     37.39                26.0         18.0             4.0   
...          ...       ...                 ...          ...             ...   
6057     -117.78     34.03                 8.0      32054.0          5290.0   
10309    -117.74     33.89                 4.0      37937.0          5471.0   
13139    -121.44     38.43                 3.0      39320.0          6210.0   
9880     -121.79     36.64                11.0      32627.0          6445.0   
15360    -117.42     33.35                14.0      25135.0          4819.0   

       population  households  median_income  median_house_value  \
5342          3.0         4.0         0.5360            350000.0   
12458         5.0         3.0         0.5360            275000.0   
3126          6.0         2.0         2.3750            137500.0   
12286         8.0         2.0         1.6250             55000.0   
18210         8.0         4.0         3.7500            375000.0   
...           ...         ...            ...                 ...   
6057      15507.0      5050.0         6.0191            253900.0   
10309     16122.0      5189.0         7.4947            366300.0   
13139     16305.0      5358.0         4.9516            153700.0   
9880      28566.0      6082.0         2.3087            118800.0   
15360     35682.0      4769.0         2.5729            134400.0   

      ocean_proximity  bedrooms_per_room  
5342        <1H OCEAN           0.333333  
12458          INLAND           0.166667  
3126           INLAND           1.000000  
12286          INLAND           0.333333  
18210        NEAR BAY           0.222222  
...               ...                ...  
6057        <1H OCEAN           0.165034  
10309       <1H OCEAN           0.144213  
13139          INLAND           0.157935  
9880        <1H OCEAN           0.197536  
15360       <1H OCEAN           0.191725  

[20640 rows x 11 columns]

In [47]:
sp500 = pd.read_csv('SP500.csv')
sp500.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1259 non-null   object 
 1   Open    1259 non-null   float64
 2   High    1259 non-null   float64
 3   Low     1259 non-null   float64
 4   Close   1259 non-null   float64
 5   Volume  1259 non-null   float64
dtypes: float64(5), object(1)
memory usage: 59.1+ KB


In [58]:
sp500.describe()

Open         High          Low        Close        Volume
count  1259.000000  1259.000000  1259.000000  1259.000000  1.259000e+03
mean   3449.673415  3470.866060  3426.301168  3449.724766  2.286974e+09
std     668.795604   672.278346   665.154072   668.903627  5.922350e+08
min    2290.710000  2300.730000  2191.860000  2237.400000  7.203000e+08
25%    2842.390000  2857.675000  2825.450000  2844.115000  1.902161e+09
50%    3280.610000  3288.130000  3253.220000  3276.020000  2.149094e+09
75%    4038.645000  4077.880000  3995.845000  4028.935000  2.515425e+09
max    4804.510000  4818.620000  4780.040000  4796.560000  5.061430e+09

In [59]:
sp500.Close.head()

0    2695.81
1    2713.06
2    2723.99
3    2743.15
4    2747.71
Name: Close, dtype: float64

In [63]:
sp500.loc[0:4, ['Date', 'Open', 'Close']]

Date     Open    Close
0  2018-01-02  2683.73  2695.81
1  2018-01-03  2697.85  2713.06
2  2018-01-04  2719.31  2723.99
3  2018-01-05  2731.33  2743.15
4  2018-01-08  2742.67  2747.71

In [66]:
sp500.loc[29]

Date        2018-02-13
Open           2646.27
High           2668.84
Low            2637.08
Close          2662.94
Volume    1929372222.0
Name: 29, dtype: object

In [70]:
sp500.loc[0:29]

Date     Open     High      Low    Close        Volume
0   2018-01-02  2683.73  2695.89  2682.36  2695.81  1.870694e+09
1   2018-01-03  2697.85  2714.37  2697.77  2713.06  1.965922e+09
2   2018-01-04  2719.31  2729.29  2719.07  2723.99  2.052922e+09
3   2018-01-05  2731.33  2743.45  2727.92  2743.15  1.798122e+09
4   2018-01-08  2742.67  2748.51  2737.60  2747.71  1.801472e+09
5   2018-01-09  2751.15  2759.14  2747.86  2751.29  1.918600e+09
6   2018-01-10  2745.55  2750.80  2736.06  2748.23  1.986861e+09
7   2018-01-11  2752.97  2767.56  2752.78  2767.56  2.022956e+09
8   2018-01-12  2770.18  2787.85  2769.64  2786.24  1.985539e+09
9   2018-01-16  2798.96  2807.54  2768.64  2776.42  2.403317e+09
10  2018-01-17  2784.99  2807.04  2778.38  2802.56  2.098917e+09
11  2018-01-18  2802.40  2805.83  2792.56  2798.03  2.045261e+09
12  2018-01-19  2802.60  2810.33  2798.08  2810.30  2.021906e+09
13  2018-01-22  2809.16  2833.03  2808.12  2832.97  1.928767e+09
14  2018-01-23  2835.05  2842.24  2830.59  2839.13  1.955361e+09
15  2018-01-24  2845.42  2852.97  2824.81  2837.54  2.230039e+09
16  2018-01-25  2846.24  2848.56  2830.94  2839.25  2.130639e+09
17  2018-01-26  2847.48  2872.87  2846.18  2872.87  1.912906e+09
18  2018-01-29  2867.23  2870.62  2851.48  2853.53  1.985461e+09
19  2018-01-30  2832.74  2837.75  2818.27  2822.43  2.217028e+09
20  2018-01-31  2832.41  2839.26  2813.04  2823.81  2.367378e+09
21  2018-02-01  2816.45  2835.96  2812.70  2821.98  2.188028e+09
22  2018-02-02  2808.92  2808.92  2759.97  2762.13  2.389517e+09
23  2018-02-05  2741.06  2763.39  2638.17  2648.94  2.935256e+09
24  2018-02-06  2614.78  2701.04  2593.07  2695.14  3.273144e+09
25  2018-02-07  2690.95  2727.67  2681.33  2681.66  2.570317e+09
26  2018-02-08  2685.01  2685.27  2580.56  2581.00  2.947467e+09
27  2018-02-09  2601.78  2638.67  2532.69  2619.55  3.155594e+09
28  2018-02-12  2636.75  2672.61  2622.45  2656.00  2.253217e+09
29  2018-02-13  2646.27  2668.84  2637.08  2662.94  1.929372e+09

In [73]:
sp500[sp500.Low <= 2800]

Date     Open     High      Low    Close        Volume
0    2018-01-02  2683.73  2695.89  2682.36  2695.81  1.870694e+09
1    2018-01-03  2697.85  2714.37  2697.77  2713.06  1.965922e+09
2    2018-01-04  2719.31  2729.29  2719.07  2723.99  2.052922e+09
3    2018-01-05  2731.33  2743.45  2727.92  2743.15  1.798122e+09
4    2018-01-08  2742.67  2748.51  2737.60  2747.71  1.801472e+09
..          ...      ...      ...      ...      ...           ...
580  2020-04-23  2810.42  2844.90  2794.26  2797.80  3.198067e+09
581  2020-04-24  2812.64  2842.71  2791.76  2836.74  2.985822e+09
587  2020-05-04  2815.01  2844.24  2797.85  2842.74  2.623967e+09
594  2020-05-13  2865.86  2874.14  2793.15  2820.00  3.538682e+09
595  2020-05-14  2794.54  2852.80  2766.64  2852.50  3.342014e+09

[278 rows x 6 columns]

In [77]:
# Znajdź dni, w których wolumen obrotów przekroczył 2 500 000 000 a cena minimalna nie przekroczyła 3000.
sp500[(sp500.Volume > 2500000000) & (sp500.Low <= 3000)]

Date     Open     High      Low    Close        Volume
23   2018-02-05  2741.06  2763.39  2638.17  2648.94  2.935256e+09
24   2018-02-06  2614.78  2701.04  2593.07  2695.14  3.273144e+09
25   2018-02-07  2690.95  2727.67  2681.33  2681.66  2.570317e+09
26   2018-02-08  2685.01  2685.27  2580.56  2581.00  2.947467e+09
27   2018-02-09  2601.78  2638.67  2532.69  2619.55  3.155594e+09
..          ...      ...      ...      ...      ...           ...
605  2020-05-29  3025.17  3049.17  2998.61  3044.31  4.372836e+09
614  2020-06-11  3123.53  3123.53  2999.49  3002.10  4.119365e+09
615  2020-06-12  3071.04  3088.42  2984.47  3041.31  3.379015e+09
616  2020-06-15  2993.76  3079.76  2965.66  3066.59  3.208286e+09
626  2020-06-29  3018.59  3053.89  2999.74  3053.24  2.650232e+09

[99 rows x 6 columns]

In [86]:
# Znajdź dni, w których wartość indeksu osiągnęła najwyższą i najniższą wartość. Wskazówka: skorzystaj z funkcji max() i min()
sp500[(sp500.High.max() == sp500.High) | (sp500.Low.min() == sp500.Low)]

Date     Open     High      Low    Close        Volume
558   2020-03-23  2290.71  2300.73  2191.86  2237.40  4.112322e+09
1009  2022-01-04  4804.51  4818.62  4774.27  4793.54  2.841121e+09

In [84]:
# Znajdź dni, w których cena otwarcia przekroczyła średnią cenę otwarcia. Wskazówka: skorzystaj z funkcji mean().
sp500[sp500.Open > sp500.Open.mean()]

Date     Open     High      Low    Close        Volume
667   2020-08-26  3449.97  3481.07  3444.15  3478.73  2.020852e+09
668   2020-08-27  3485.14  3501.38  3468.35  3484.55  2.327432e+09
669   2020-08-28  3494.69  3509.23  3484.32  3508.01  2.047771e+09
670   2020-08-31  3509.73  3514.77  3493.25  3500.31  2.545948e+09
671   2020-09-01  3507.44  3528.03  3494.60  3526.65  2.246656e+09
...          ...      ...      ...      ...      ...           ...
1254  2022-12-23  3815.11  3845.80  3797.01  3844.82  1.579203e+09
1255  2022-12-27  3843.34  3846.65  3813.22  3829.25  1.753562e+09
1256  2022-12-28  3829.56  3848.32  3780.78  3783.22  1.741219e+09
1257  2022-12-29  3805.45  3858.19  3805.45  3849.28  1.734475e+09
1258  2022-12-30  3829.06  3839.85  3800.34  3839.50  1.704123e+09

[558 rows x 6 columns]

In [90]:
# Stwórz nową kolumnę zawierającą różnicę między ceną maksymalną a minimalną danego dnia.
sp500["low_max_diff"] = sp500.High - sp500.Low
sp500.head()

Date     Open     High      Low    Close        Volume  low_max_diff
0  2018-01-02  2683.73  2695.89  2682.36  2695.81  1.870694e+09         13.53
1  2018-01-03  2697.85  2714.37  2697.77  2713.06  1.965922e+09         16.60
2  2018-01-04  2719.31  2729.29  2719.07  2723.99  2.052922e+09         10.22
3  2018-01-05  2731.33  2743.45  2727.92  2743.15  1.798122e+09         15.53
4  2018-01-08  2742.67  2748.51  2737.60  2747.71  1.801472e+09         10.91

In [99]:
# Stwórz nową kolumnę zawierającą odchylenie ceny otwarcia od średniej ceny otwarcia.
sp500['mean_open_diff'] = sp500.Open.mean() - sp500.Open
sp500.head()

Date     Open     High      Low    Close        Volume  low_max_diff  \
0  2018-01-02  2683.73  2695.89  2682.36  2695.81  1.870694e+09         13.53   
1  2018-01-03  2697.85  2714.37  2697.77  2713.06  1.965922e+09         16.60   
2  2018-01-04  2719.31  2729.29  2719.07  2723.99  2.052922e+09         10.22   
3  2018-01-05  2731.33  2743.45  2727.92  2743.15  1.798122e+09         15.53   
4  2018-01-08  2742.67  2748.51  2737.60  2747.71  1.801472e+09         10.91   

     std_open  mean_open_diff  
0  765.943415      765.943415  
1  751.823415      751.823415  
2  730.363415      730.363415  
3  718.343415      718.343415  
4  707.003415      707.003415

In [101]:
# Usuń kolumnę Volume
sp500.drop(["Volume"], axis='columns').head()

Date     Open     High      Low    Close  low_max_diff    std_open  \
0  2018-01-02  2683.73  2695.89  2682.36  2695.81         13.53  765.943415   
1  2018-01-03  2697.85  2714.37  2697.77  2713.06         16.60  751.823415   
2  2018-01-04  2719.31  2729.29  2719.07  2723.99         10.22  730.363415   
3  2018-01-05  2731.33  2743.45  2727.92  2743.15         15.53  718.343415   
4  2018-01-08  2742.67  2748.51  2737.60  2747.71         10.91  707.003415   

   mean_open_diff  
0      765.943415  
1      751.823415  
2      730.363415  
3      718.343415  
4      707.003415

In [109]:
# Usuń wiersze zawierające notowania z roku 2018.
sp2018 = sp500[sp500.Date.str.contains('2018')]
sp500.drop(sp2018.index)

Date     Open     High      Low    Close        Volume  \
251   2019-01-02  2476.96  2519.49  2467.47  2510.03  2.073978e+09   
252   2019-01-03  2491.92  2493.14  2443.96  2447.89  2.123811e+09   
253   2019-01-04  2474.33  2538.07  2474.33  2531.94  2.340783e+09   
254   2019-01-07  2535.61  2566.16  2524.56  2549.69  2.280394e+09   
255   2019-01-08  2568.11  2579.82  2547.56  2574.41  2.268350e+09   
...          ...      ...      ...      ...      ...           ...   
1254  2022-12-23  3815.11  3845.80  3797.01  3844.82  1.579203e+09   
1255  2022-12-27  3843.34  3846.65  3813.22  3829.25  1.753562e+09   
1256  2022-12-28  3829.56  3848.32  3780.78  3783.22  1.741219e+09   
1257  2022-12-29  3805.45  3858.19  3805.45  3849.28  1.734475e+09   
1258  2022-12-30  3829.06  3839.85  3800.34  3839.50  1.704123e+09   

      low_max_diff    std_open  mean_open_diff  
251          52.02  972.713415      972.713415  
252          49.18  957.753415      957.753415  
253          63.74  975.343415      975.343415  
254          41.60  914.063415      914.063415  
255          32.26  881.563415      881.563415  
...            ...         ...             ...  
1254         48.79 -365.436585     -365.436585  
1255         33.43 -393.666585     -393.666585  
1256         67.54 -379.886585     -379.886585  
1257         52.74 -355.776585     -355.776585  
1258         39.51 -379.386585     -379.386585  

[1008 rows x 9 columns]

In [110]:
spJan = pd.read_csv('SP500Jan2023.csv')
pd.concat([sp500, spJan])

Date     Open     High      Low    Close        Volume  \
0   2018-01-02  2683.73  2695.89  2682.36  2695.81  1.870694e+09   
1   2018-01-03  2697.85  2714.37  2697.77  2713.06  1.965922e+09   
2   2018-01-04  2719.31  2729.29  2719.07  2723.99  2.052922e+09   
3   2018-01-05  2731.33  2743.45  2727.92  2743.15  1.798122e+09   
4   2018-01-08  2742.67  2748.51  2737.60  2747.71  1.801472e+09   
..         ...      ...      ...      ...      ...           ...   
15  2023-01-25  3982.71  4019.55  3949.06  4016.22  2.427959e+09   
16  2023-01-26  4036.08  4061.57  4013.29  4060.43  2.436722e+09   
17  2023-01-27  4053.72  4094.21  4048.70  4070.56  2.573674e+09   
18  2023-01-30  4049.27  4063.85  4015.55  4017.77  2.323118e+09   
19  2023-01-31  4020.85  4077.16  4020.44  4076.60  2.868839e+09   

    low_max_diff    std_open  mean_open_diff  
0          13.53  765.943415      765.943415  
1          16.60  751.823415      751.823415  
2          10.22  730.363415      730.363415  
3          15.53  718.343415      718.343415  
4          10.91  707.003415      707.003415  
..           ...         ...             ...  
15           NaN         NaN             NaN  
16           NaN         NaN             NaN  
17           NaN         NaN             NaN  
18           NaN         NaN             NaN  
19           NaN         NaN             NaN  

[1279 rows x 9 columns]

In [111]:
spJan = pd.read_csv('SP500Jan2023.csv')
pd.concat([sp500, spJan], join="inner")

Date     Open     High      Low    Close        Volume
0   2018-01-02  2683.73  2695.89  2682.36  2695.81  1.870694e+09
1   2018-01-03  2697.85  2714.37  2697.77  2713.06  1.965922e+09
2   2018-01-04  2719.31  2729.29  2719.07  2723.99  2.052922e+09
3   2018-01-05  2731.33  2743.45  2727.92  2743.15  1.798122e+09
4   2018-01-08  2742.67  2748.51  2737.60  2747.71  1.801472e+09
..         ...      ...      ...      ...      ...           ...
15  2023-01-25  3982.71  4019.55  3949.06  4016.22  2.427959e+09
16  2023-01-26  4036.08  4061.57  4013.29  4060.43  2.436722e+09
17  2023-01-27  4053.72  4094.21  4048.70  4070.56  2.573674e+09
18  2023-01-30  4049.27  4063.85  4015.55  4017.77  2.323118e+09
19  2023-01-31  4020.85  4077.16  4020.44  4076.60  2.868839e+09

[1279 rows x 6 columns]